using Assisticant;

namespace Assisticant.UnitTest.ContactListData
{
    public class Contact
    {
        private string _firstName;
        private string _lastName;

        #region Observable properties
        // Generated by Update Controls --------------------------------
        private Observable _indFirstName = new Observable();
        private Observable _indLastName = new Observable();

        public string FirstName
        {
            get { _indFirstName.OnGet(); return _firstName; }
            set { _indFirstName.OnSet(); _firstName = value; }
        }

        public string LastName
        {
            get { _indLastName.OnGet(); return _lastName; }
            set { _indLastName.OnSet(); _lastName = value; }
        }
        // End generated code --------------------------------
        #endregion
    }
}
