using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Assisticant.SourceGenerators.GeneratorSupport;

namespace Assisticant.SourceGenerators
{
    /// <summary>
    /// ViewModel layer. Turns a <c>[Command]</c>-decorated method into an
    /// <c>ICommand</c>-typed property - Assisticant's answer to MAUI's (and WPF's)
    /// <c>Button.Command</c>/<c>CommandParameter</c> binding:
    ///
    ///     [Command] private void ClearSelection() =&gt; IsSelected = false;
    ///     private bool CanClearSelection() =&gt; IsSelected;
    ///
    /// becomes:
    ///
    ///     private GeneratedCommand? __clearSelectionCommandField;
    ///     public ICommand ClearSelectionCommand =&gt;
    ///         __clearSelectionCommandField ??= new GeneratedCommand(ClearSelection, CanClearSelection);
    ///
    /// <c>CanClearSelection</c> is discovered purely by naming convention - a
    /// parameterless, bool-returning method named "Can" + the command method's name,
    /// on the same class - matching Assisticant's existing reflection-based
    /// <c>Metas/CommandMeta.cs</c> convention; it isn't itself attributed. If no such
    /// method exists, the command is always executable.
    ///
    /// <b>Why this needs no manual "RefreshCanExecutes()" bookkeeping</b> (the pattern
    /// MAUI's own docs show for its own <c>Command</c> class): the generated
    /// <see cref="GeneratedCommand"/> wraps the CanExecute predicate in a
    /// <c>Computed&lt;bool&gt;</c> and raises <c>CanExecuteChanged</c> (deferred through
    /// <c>UpdateScheduler</c>, same reasoning as <see cref="ComputedGenerator"/>)
    /// automatically whenever anything that predicate reads changes - the same
    /// dependency tracking every other generator in this prototype relies on, just
    /// aimed at <c>ICommand</c> instead of a property.
    ///
    /// <b>Scope of this prototype:</b> only parameterless, void-returning methods are
    /// supported - not MAUI's <c>Command&lt;T&gt;</c>/<c>CommandParameter</c> pattern.
    /// A parameter supplied at Execute/CanExecute call time by the platform isn't a
    /// value Assisticant's dependency graph can track the way a <c>Computed&lt;T&gt;</c>
    /// tracks a captured no-argument delegate's reads, so it doesn't fit this
    /// generator's model without more design work; seeing ASSISTICANT302 is
    /// intentional, not a missing feature to route around.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class CommandGenerator : IIncrementalGenerator
    {
        private const string CommandAttributeFullName = "Assisticant.Fields.CommandAttribute";

        private const string AttributeSource = @"// <auto-generated/>
#nullable enable

namespace Assisticant.Fields
{
    /// <summary>
    /// Generates an ICommand-typed property backed by <see cref=""GeneratedCommand""/> -
    /// Assisticant's answer to a view's Command/CommandParameter binding (e.g.
    /// Button.Command on MAUI or WPF).
    ///
    /// Apply it to a parameterless, void-returning method:
    ///
    ///     [Command] private void ClearSelection() =&gt; IsSelected = false;
    ///
    /// generates a property named by appending ""Command"" to the method's name (here,
    /// ""ClearSelectionCommand""), or by the name given to the attribute:
    /// [Command(""PropertyName"")]. If a parameterless, bool-returning method named
    /// ""Can"" + the method's name exists on the same class (e.g. ""CanClearSelection""),
    /// it's used as the CanExecute predicate automatically - no attribute needed on it.
    /// The containing type (and every enclosing type, if nested) must be declared
    /// 'partial'.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    internal sealed class CommandAttribute : global::System.Attribute
    {
        public CommandAttribute() { }

        public CommandAttribute(string propertyName) => PropertyName = propertyName;

        public string? PropertyName { get; }
    }

    /// <summary>
    /// The ICommand implementation [Command]-generated properties are backed by. Not
    /// intended to be constructed directly.
    ///
    /// When a canExecute predicate is supplied, it's wrapped in a Computed&lt;bool&gt; so
    /// CanExecuteChanged is raised automatically (deferred through UpdateScheduler,
    /// for the same reason [Computed]'s PropertyChanged raise is - see
    /// ComputedGenerator's doc comment) whenever anything canExecute reads changes.
    /// Unlike .NET MAUI's own Command class, nothing needs to manually call
    /// ChangeCanExecute() or re-raise CanExecuteChanged after a mutation - the
    /// dependency is discovered, not declared.
    /// </summary>
    public sealed class GeneratedCommand : global::System.Windows.Input.ICommand
    {
        private readonly global::System.Action _execute;
        private readonly Computed<bool>? _canExecute;

        public GeneratedCommand(global::System.Action execute, global::System.Func<bool>? canExecute)
        {
            _execute = execute;
            if (canExecute != null)
            {
                _canExecute = new Computed<bool>(canExecute);
                _canExecute.Invalidated += () =>
                    global::Assisticant.UpdateScheduler.ScheduleUpdate(() =>
                        CanExecuteChanged?.Invoke(this, global::System.EventArgs.Empty));
            }
        }

        public event global::System.EventHandler? CanExecuteChanged;

        public bool CanExecute(object? parameter) => _canExecute?.Value ?? true;

        public void Execute(object? parameter) => _execute();
    }
}
";

        private static readonly DiagnosticDescriptor TypeNotPartialDiagnostic = new DiagnosticDescriptor(
            id: "ASSISTICANT301",
            title: "Containing type must be partial",
            messageFormat: "Type '{0}' must be declared 'partial' to use [Command] on method '{1}'",
            category: "Assisticant.SourceGenerators",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor MethodHasParametersDiagnostic = new DiagnosticDescriptor(
            id: "ASSISTICANT302",
            title: "Method must have no parameters",
            messageFormat: "Method '{0}' is decorated with [Command] but declares parameters; this prototype doesn't support a CommandParameter-typed command (see CommandGenerator's doc comment for why)",
            category: "Assisticant.SourceGenerators",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor MethodNotVoidDiagnostic = new DiagnosticDescriptor(
            id: "ASSISTICANT303",
            title: "Method must return void",
            messageFormat: "Method '{0}' is decorated with [Command] but returns a value; an ICommand's Execute cannot return anything",
            category: "Assisticant.SourceGenerators",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx =>
                ctx.AddSource("CommandAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

            IncrementalValuesProvider<MethodResult> results = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    CommandAttributeFullName,
                    predicate: static (node, _) => node is MethodDeclarationSyntax,
                    transform: static (ctx, ct) => Analyze(ctx, ct));

            context.RegisterSourceOutput(results.Collect(), static (spc, all) => Execute(spc, all));
        }

        private static MethodResult Analyze(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
        {
            var method = (IMethodSymbol)ctx.TargetSymbol;
            var location = ctx.TargetNode.GetLocation();

            var typeChain = GetPartialTypeChainOrNull(ctx.TargetNode, method.Name, location, TypeNotPartialDiagnostic, out var typeError);
            if (typeChain == null)
                return MethodResult.Error(typeError!);

            if (method.Parameters.Length > 0)
                return MethodResult.Error(Diagnostic.Create(MethodHasParametersDiagnostic, location, method.Name));

            if (!method.ReturnsVoid)
                return MethodResult.Error(Diagnostic.Create(MethodNotVoidDiagnostic, location, method.Name));

            var propertyName = GetExplicitPropertyName(method) ?? (method.Name + "Command");
            var ns = GetNamespace(method.ContainingType);
            var backingFieldName = "__" + char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1) + "Field";

            var canExecuteMethodName = FindCanExecuteMethodName(method);

            return MethodResult.Success(ns, typeChain, method.Name, propertyName, backingFieldName, canExecuteMethodName);
        }

        private static string? GetExplicitPropertyName(IMethodSymbol method)
        {
            var attribute = method.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == CommandAttributeFullName);
            if (attribute is { ConstructorArguments.Length: > 0 } &&
                attribute.ConstructorArguments[0].Value is string explicitName &&
                !string.IsNullOrWhiteSpace(explicitName))
            {
                return explicitName;
            }
            return null;
        }

        /// <summary>
        /// Looks for a parameterless, bool-returning method named "Can" + the command
        /// method's name on the same containing type - matching the naming convention
        /// Metas/CommandMeta.cs already uses for the reflection-based proxy.
        /// </summary>
        private static string? FindCanExecuteMethodName(IMethodSymbol method)
        {
            var canExecuteName = "Can" + method.Name;
            var candidate = method.ContainingType.GetMembers(canExecuteName)
                .OfType<IMethodSymbol>()
                .FirstOrDefault(m => m.Parameters.Length == 0 && m.ReturnType.SpecialType == SpecialType.System_Boolean);
            return candidate?.Name;
        }

        private static void Execute(SourceProductionContext spc, ImmutableArray<MethodResult> all)
        {
            foreach (var result in all)
            {
                if (result.Diagnostic is { } diagnostic)
                    spc.ReportDiagnostic(diagnostic);
            }

            var successes = all.Where(r => r.Diagnostic == null).ToList();

            var groups = successes.GroupBy(r => r.Namespace + "|" + string.Join("+", r.TypeChain!.Select(t => t.Name)));

            foreach (var group in groups)
            {
                var first = group.First();
                var source = RenderType(first.Namespace, first.TypeChain!, group.ToList());
                var hintName = string.Join(".", first.TypeChain!.Select(t => SanitizeForFileName(t.Name))) + ".Command.g.cs";
                spc.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
            }
        }

        private static string RenderType(string ns, List<TypeFrame> typeChain, List<MethodResult> members)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by Assisticant.SourceGenerators.CommandGenerator from [Command] methods.");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(ns);
            int indent = 0;

            if (hasNamespace)
            {
                sb.Append("namespace ").Append(ns).AppendLine();
                sb.AppendLine("{");
                indent = 1;
            }

            foreach (var frame in typeChain)
            {
                Indent(sb, indent).Append("partial ").Append(frame.Keyword).Append(' ').Append(frame.Name).AppendLine();
                Indent(sb, indent).AppendLine("{");
                indent++;
            }

            foreach (var member in members)
            {
                Indent(sb, indent)
                    .Append("private global::Assisticant.Fields.GeneratedCommand? ")
                    .Append(member.BackingFieldName).AppendLine(";");
                Indent(sb, indent)
                    .Append("public global::System.Windows.Input.ICommand ").Append(member.PropertyName)
                    .Append(" => ").Append(member.BackingFieldName)
                    .Append(" ??= new global::Assisticant.Fields.GeneratedCommand(").Append(member.MethodName).Append(", ")
                    .Append(member.CanExecuteMethodName ?? "null").AppendLine(");");
                sb.AppendLine();
            }

            for (int i = typeChain.Count - 1; i >= 0; i--)
            {
                indent--;
                Indent(sb, indent).AppendLine("}");
            }

            if (hasNamespace)
                sb.AppendLine("}");

            return sb.ToString();
        }

        private sealed class MethodResult
        {
            public string Namespace = "";
            public List<TypeFrame>? TypeChain;
            public string MethodName = "";
            public string PropertyName = "";
            public string BackingFieldName = "";
            public string? CanExecuteMethodName;
            public Diagnostic? Diagnostic;

            public static MethodResult Success(
                string ns, List<TypeFrame> typeChain, string methodName, string propertyName,
                string backingFieldName, string? canExecuteMethodName) =>
                new MethodResult
                {
                    Namespace = ns,
                    TypeChain = typeChain,
                    MethodName = methodName,
                    PropertyName = propertyName,
                    BackingFieldName = backingFieldName,
                    CanExecuteMethodName = canExecuteMethodName,
                };

            public static MethodResult Error(Diagnostic diagnostic) =>
                new MethodResult { Diagnostic = diagnostic };
        }
    }
}
