using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Assisticant.SourceGenerators.GeneratorSupport;

namespace Assisticant.SourceGenerators
{
    /// <summary>
    /// ViewModel layer. Turns an <c>[Computed]</c>-decorated method into a read-only
    /// property backed by <c>Computed&lt;T&gt;</c> - Assisticant's dependent variables.
    ///
    /// <b>Model/ViewModel separation:</b> by default a ViewModel holds no
    /// <c>Observable&lt;T&gt;</c> of its own (see <see cref="ObservableGenerator"/>'s
    /// doc comment) - it takes one or more Models through its constructor, the same
    /// way a View takes a ViewModel through its DataContext/<c>ForView.Wrap</c> - and
    /// derives everything it exposes from them. This is a strong default, not a hard
    /// rule: a ViewModel can also carry its own [Observable] state for things no Model
    /// would ever care about (e.g. "is this row selected"), and a [Computed] property
    /// can just as well depend on one of those as on an injected Model's property -
    /// dependency tracking doesn't care which class or layer an Observable/Computed
    /// lives in; that's purely a convention this generator doesn't enforce.
    ///
    ///     public partial class PersonViewModel
    ///     {
    ///         private readonly Person _person; // injected Model
    ///         public PersonViewModel(Person person) =&gt; _person = person;
    ///
    ///         [Computed] private string ComputeGreeting() =&gt; $"Hello, {_person.Name}!";
    ///     }
    ///
    /// becomes:
    ///
    ///     partial class PersonViewModel
    ///     {
    ///         private readonly Computed&lt;string&gt; __greetingField = new Computed&lt;string&gt;(ComputeGreeting);
    ///         public string Greeting =&gt; __greetingField.Value;
    ///     }
    ///
    /// The method must take no parameters and not return void (it becomes the
    /// Func&lt;T&gt; passed to Computed&lt;T&gt;'s constructor). Because a property can't
    /// share its name with the method that computes it, the property name is derived
    /// by stripping a leading "Compute" or "Get" prefix (or given explicitly via
    /// [Computed("PropertyName")]).
    ///
    /// Add <c>[NotifyPropertyChanged]</c> to the class (see
    /// <see cref="NotifyPropertyChangedGenerator"/>) to have each [Computed] property
    /// also raise <c>PropertyChanged</c> (asynchronously, via <c>UpdateScheduler</c>)
    /// whenever its backing <c>Computed&lt;T&gt;</c> invalidates.
    ///
    /// This is a prototype - see the caveats on <see cref="ObservableGenerator"/>,
    /// which apply here too.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class ComputedGenerator : IIncrementalGenerator
    {
        private const string ComputedAttributeFullName = "Assisticant.Fields.ComputedAttribute";

        private const string AttributeSource = @"// <auto-generated/>
#nullable enable

namespace Assisticant.Fields
{
    /// <summary>
    /// Generates a read-only property backed by <see cref=""Computed{T}""/> - Assisticant's
    /// dependent variables. Belongs on ViewModel classes only, deriving from an injected
    /// Model; see [Observable] for Models.
    ///
    /// Apply it to a parameterless, non-void method:
    ///
    ///     [Computed] private string ComputeGreeting() =&gt; $""Hello, {_person.Name}!"";
    ///
    /// generates a property named by stripping the method's leading ""Compute""/""Get""
    /// prefix (here, ""Greeting""), or by the name given to the attribute:
    /// [Computed(""PropertyName"")]. The containing type (and every enclosing type, if
    /// nested) must be declared 'partial'.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    internal sealed class ComputedAttribute : global::System.Attribute
    {
        public ComputedAttribute() { }

        public ComputedAttribute(string propertyName) => PropertyName = propertyName;

        public string? PropertyName { get; }
    }
}
";

        private static readonly DiagnosticDescriptor TypeNotPartialDiagnostic = new DiagnosticDescriptor(
            id: "ASSISTICANT101",
            title: "Containing type must be partial",
            messageFormat: "Type '{0}' must be declared 'partial' to use [Computed] on method '{1}'",
            category: "Assisticant.SourceGenerators",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor MethodHasParametersDiagnostic = new DiagnosticDescriptor(
            id: "ASSISTICANT102",
            title: "Method must have no parameters",
            messageFormat: "Method '{0}' is decorated with [Computed] but declares parameters; it becomes a Func<T> with no arguments",
            category: "Assisticant.SourceGenerators",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor MethodReturnsVoidDiagnostic = new DiagnosticDescriptor(
            id: "ASSISTICANT103",
            title: "Method must return a value",
            messageFormat: "Method '{0}' is decorated with [Computed] but returns void; it must return the computed value",
            category: "Assisticant.SourceGenerators",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor CannotDeriveNameDiagnostic = new DiagnosticDescriptor(
            id: "ASSISTICANT104",
            title: "Cannot derive a property name",
            messageFormat: "Cannot derive a property name for method '{0}'; rename it with a 'Compute' or 'Get' prefix (e.g. 'Compute{0}'), or specify one explicitly with [Computed(\"PropertyName\")]",
            category: "Assisticant.SourceGenerators",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly string[] StrippablePrefixes = { "Compute", "Get" };

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx =>
                ctx.AddSource("ComputedAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

            IncrementalValuesProvider<MethodResult> results = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    ComputedAttributeFullName,
                    predicate: static (node, _) => node is MethodDeclarationSyntax,
                    transform: static (ctx, ct) => Analyze(ctx, ct));

            context.RegisterSourceOutput(results.Collect(), static (spc, all) => Execute(spc, all));
        }

        private static MethodResult Analyze(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
        {
            var method = (IMethodSymbol)ctx.TargetSymbol;
            var location = ctx.TargetNode.GetLocation();

            var typeChain = GetPartialTypeChainOrNull(ctx.TargetNode, method.Name, location, TypeNotPartialDiagnostic, out var typeError);
            if (typeChain == null)
                return MethodResult.Error(typeError!);

            if (method.Parameters.Length > 0)
                return MethodResult.Error(Diagnostic.Create(MethodHasParametersDiagnostic, location, method.Name));

            if (method.ReturnsVoid)
                return MethodResult.Error(Diagnostic.Create(MethodReturnsVoidDiagnostic, location, method.Name));

            string? candidateName = GetExplicitPropertyName(method) ?? DerivePropertyName(method.Name);
            if (string.IsNullOrEmpty(candidateName) || candidateName == method.Name)
                return MethodResult.Error(Diagnostic.Create(CannotDeriveNameDiagnostic, location, method.Name));

            string propertyName = candidateName!;
            var elementTypeDisplay = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var backingFieldName = "__" + char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1) + "Field";
            var ns = GetNamespace(method.ContainingType);
            var notifiesPropertyChanged = method.ContainingType.GetAttributes()
                .Any(a => a.AttributeClass?.ToDisplayString() == NotifyPropertyChangedAttributeFullName);

            return MethodResult.Success(ns, typeChain, method.Name, propertyName, elementTypeDisplay, backingFieldName, notifiesPropertyChanged);
        }

        private static string? GetExplicitPropertyName(IMethodSymbol method)
        {
            var attribute = method.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == ComputedAttributeFullName);
            if (attribute is { ConstructorArguments.Length: > 0 } &&
                attribute.ConstructorArguments[0].Value is string explicitName &&
                !string.IsNullOrWhiteSpace(explicitName))
            {
                return explicitName;
            }
            return null;
        }

        private static string? DerivePropertyName(string methodName)
        {
            foreach (var prefix in StrippablePrefixes)
            {
                if (methodName.Length > prefix.Length && methodName.StartsWith(prefix, StringComparison.Ordinal))
                    return methodName.Substring(prefix.Length);
            }
            return null;
        }

        private static void Execute(SourceProductionContext spc, ImmutableArray<MethodResult> all)
        {
            foreach (var result in all)
            {
                if (result.Diagnostic is { } diagnostic)
                    spc.ReportDiagnostic(diagnostic);
            }

            var successes = all.Where(r => r.Diagnostic == null).ToList();

            var groups = successes.GroupBy(r => r.Namespace + "|" + string.Join("+", r.TypeChain!.Select(t => t.Name)));

            foreach (var group in groups)
            {
                var first = group.First();
                var source = RenderType(first.Namespace, first.TypeChain!, group.ToList());
                var hintName = string.Join(".", first.TypeChain!.Select(t => SanitizeForFileName(t.Name))) + ".Computed.g.cs";
                spc.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
            }
        }

        private static string RenderType(string ns, List<TypeFrame> typeChain, List<MethodResult> members)
        {
            bool notifies = members[0].NotifiesPropertyChanged;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by Assisticant.SourceGenerators.ComputedGenerator from [Computed] methods.");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(ns);
            int indent = 0;

            if (hasNamespace)
            {
                sb.Append("namespace ").Append(ns).AppendLine();
                sb.AppendLine("{");
                indent = 1;
            }

            foreach (var frame in typeChain)
            {
                Indent(sb, indent).Append("partial ").Append(frame.Keyword).Append(' ').Append(frame.Name).AppendLine();
                Indent(sb, indent).AppendLine("{");
                indent++;
            }

            // The PropertyChanged event, the interface's presence on the class, and the
            // __RaisePropertyChanged helper called below are all owned by
            // NotifyPropertyChangedGenerator (see its doc comment for why this generator
            // doesn't declare them itself even when `notifies` is true here).
            foreach (var member in members)
            {
                // A field initializer can't reference an instance method (CS0236 -
                // "this" isn't available yet), so the Computed<T> is constructed
                // lazily, on first access, instead of via a field initializer or a
                // generated constructor (which would need to run no matter which of
                // the user's own constructors was called).
                Indent(sb, indent)
                    .Append("private global::Assisticant.Fields.Computed<").Append(member.ElementType).Append(">? ")
                    .Append(member.BackingFieldName).AppendLine(";");

                if (notifies)
                {
                    // Raising PropertyChanged is deferred through UpdateScheduler rather
                    // than invoked directly from the Invalidated handler, even though
                    // this event carries no value to read: Observable<T>.Value's setter
                    // raises invalidation (which cascades into this Computed<T>'s
                    // Invalidated) BEFORE storing the new value, and some UI dispatchers
                    // (documented on UpdateScheduler.Initialize) run queued work inline
                    // when already on the UI thread. Deferring - the same way
                    // ComputedSubscription and the WPF proxy's MemberSlot already do -
                    // guarantees the eventual re-read sees the new value regardless of
                    // what the host binding infrastructure's own dispatch does.
                    Indent(sb, indent)
                        .Append("public ").Append(member.ElementType).Append(' ').Append(member.PropertyName)
                        .Append(" => (").Append(member.BackingFieldName)
                        .Append(" ??= __Create").Append(member.PropertyName).AppendLine("Field()).Value;");
                    Indent(sb, indent)
                        .Append("private global::Assisticant.Fields.Computed<").Append(member.ElementType).Append("> __Create")
                        .Append(member.PropertyName).AppendLine("Field()");
                    Indent(sb, indent).AppendLine("{");
                    Indent(sb, indent + 1)
                        .Append("var computed = new global::Assisticant.Fields.Computed<").Append(member.ElementType).Append(">(")
                        .Append(member.MethodName).AppendLine(");");
                    Indent(sb, indent + 1)
                        .Append("computed.Invalidated += () => global::Assisticant.UpdateScheduler.ScheduleUpdate(() => __RaisePropertyChanged(\"")
                        .Append(member.PropertyName).AppendLine("\"));");
                    Indent(sb, indent + 1).AppendLine("return computed;");
                    Indent(sb, indent).AppendLine("}");
                }
                else
                {
                    Indent(sb, indent)
                        .Append("public ").Append(member.ElementType).Append(' ').Append(member.PropertyName)
                        .Append(" => (").Append(member.BackingFieldName)
                        .Append(" ??= new global::Assisticant.Fields.Computed<").Append(member.ElementType).Append(">(")
                        .Append(member.MethodName).Append(")).Value;").AppendLine();
                }
                sb.AppendLine();
            }

            for (int i = typeChain.Count - 1; i >= 0; i--)
            {
                indent--;
                Indent(sb, indent).AppendLine("}");
            }

            if (hasNamespace)
                sb.AppendLine("}");

            return sb.ToString();
        }

        private sealed class MethodResult
        {
            public string Namespace = "";
            public List<TypeFrame>? TypeChain;
            public string MethodName = "";
            public string PropertyName = "";
            public string ElementType = "";
            public string BackingFieldName = "";
            public bool NotifiesPropertyChanged;
            public Diagnostic? Diagnostic;

            public static MethodResult Success(
                string ns, List<TypeFrame> typeChain, string methodName, string propertyName, string elementType,
                string backingFieldName, bool notifiesPropertyChanged) =>
                new MethodResult
                {
                    Namespace = ns,
                    TypeChain = typeChain,
                    MethodName = methodName,
                    PropertyName = propertyName,
                    ElementType = elementType,
                    BackingFieldName = backingFieldName,
                    NotifiesPropertyChanged = notifiesPropertyChanged,
                };

            public static MethodResult Error(Diagnostic diagnostic) =>
                new MethodResult { Diagnostic = diagnostic };
        }
    }
}
