using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Assisticant.SourceGenerators.GeneratorSupport;

namespace Assisticant.SourceGenerators
{
    /// <summary>
    /// Cross-cutting layer. Applied to a ViewModel (or Model) class, <c>[NotifyPropertyChanged]</c>
    /// generates an <c>INotifyPropertyChanged</c> implementation: the <c>PropertyChanged</c>
    /// event and a private <c>__RaisePropertyChanged(string)</c> helper.
    ///
    /// This is deliberately its own generator, independent of <see cref="ObservableGenerator"/>
    /// and <see cref="ComputedGenerator"/>, rather than something either of them emits directly.
    /// A class can combine <c>[Observable]</c> properties, <c>[Computed]</c> methods, and
    /// <c>[NotifyPropertyChanged]</c> all at once - Assisticant's Model/ViewModel separation is
    /// a strong default, not an axiom, and there are reasonable cases for a ViewModel to hold
    /// some of its own <c>Observable&lt;T&gt;</c> state directly (e.g. pure UI/interaction state
    /// like "is this row selected" that no Model would ever care about). If both of those
    /// generators each independently emitted the event and helper whenever they saw
    /// [NotifyPropertyChanged], a class using both would get two conflicting definitions of
    /// the same members. Instead, this generator alone owns that scaffolding; the other two
    /// only ever call <c>__RaisePropertyChanged</c>, never declare it.
    ///
    /// See <see cref="ObservableGenerator"/> and <see cref="ComputedGenerator"/> for how each
    /// participates: an <c>[Observable]</c> property raises it (deferred through
    /// <c>UpdateScheduler</c>) directly from its own setter when the value actually changes; a
    /// <c>[Computed]</c> property raises it (also deferred) when its backing <c>Computed&lt;T&gt;</c>
    /// invalidates - which happens whether the dependency is an injected Model's [Observable]
    /// property or another [Observable] property on this same class.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class NotifyPropertyChangedGenerator : IIncrementalGenerator
    {
        private const string AttributeSource = @"// <auto-generated/>
#nullable enable

namespace Assisticant.Fields
{
    /// <summary>
    /// Applied to a class (alongside [Observable] properties and/or [Computed] methods) to
    /// generate an INotifyPropertyChanged implementation: a PropertyChanged event, and a
    /// helper that both [Observable] and [Computed] call to raise it when their value
    /// actually changes. This is what lets an object be bound directly with XAML {Binding} -
    /// e.g. on MAUI, whose binding infrastructure (unlike WPF's ICustomTypeDescriptor-based
    /// ForView.Wrap proxy) has no wrapper layer and requires the bound object to implement
    /// INotifyPropertyChanged itself for live (OneWay/TwoWay) updates.
    ///
    /// Only apply this to classes actually bound this way - e.g. not to a ViewModel only
    /// ever wrapped by WPF's ForView.Wrap (whose proxy already raises its own
    /// PropertyChanged) or only read directly in unit tests. Every such class pays for an
    /// event field and a subscription per [Computed] member; opting in only where it's used
    /// keeps that cost out of the rest. The containing type (and every enclosing type, if
    /// nested) must be declared 'partial'.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class NotifyPropertyChangedAttribute : global::System.Attribute
    {
    }
}
";

        private static readonly DiagnosticDescriptor TypeNotPartialDiagnostic = new DiagnosticDescriptor(
            id: "ASSISTICANT201",
            title: "Type must be partial",
            messageFormat: "Type '{0}' must be declared 'partial' to use [NotifyPropertyChanged]",
            category: "Assisticant.SourceGenerators",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx =>
                ctx.AddSource("NotifyPropertyChangedAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

            IncrementalValuesProvider<ClassResult> results = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    NotifyPropertyChangedAttributeFullName,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, ct) => Analyze(ctx, ct));

            context.RegisterSourceOutput(results, static (spc, result) => Execute(spc, result));
        }

        private static ClassResult Analyze(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
        {
            var type = (INamedTypeSymbol)ctx.TargetSymbol;
            var location = ctx.TargetNode.GetLocation();

            var typeChain = GetPartialTypeChainOrNull(ctx.TargetNode, type.Name, location, TypeNotPartialDiagnostic, out var typeError);
            if (typeChain == null)
                return ClassResult.Error(typeError!);

            var ns = GetNamespace(type);
            return ClassResult.Success(ns, typeChain);
        }

        private static void Execute(SourceProductionContext spc, ClassResult result)
        {
            if (result.Diagnostic is { } diagnostic)
            {
                spc.ReportDiagnostic(diagnostic);
                return;
            }

            var source = RenderType(result.Namespace, result.TypeChain!);
            var hintName = string.Join(".", result.TypeChain!.Select(t => SanitizeForFileName(t.Name))) + ".NotifyPropertyChanged.g.cs";
            spc.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
        }

        private static string RenderType(string ns, List<TypeFrame> typeChain)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by Assisticant.SourceGenerators.NotifyPropertyChangedGenerator from [NotifyPropertyChanged].");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(ns);
            int indent = 0;

            if (hasNamespace)
            {
                sb.Append("namespace ").Append(ns).AppendLine();
                sb.AppendLine("{");
                indent = 1;
            }

            for (int i = 0; i < typeChain.Count; i++)
            {
                var frame = typeChain[i];
                Indent(sb, indent).Append("partial ").Append(frame.Keyword).Append(' ').Append(frame.Name);
                // Only the innermost declaration - the one actually decorated with
                // [NotifyPropertyChanged] - needs to add the interface; C# merges base
                // lists across partial declarations, so this doesn't need to be repeated
                // on (or match) the user's own declaration.
                if (i == typeChain.Count - 1)
                    sb.Append(" : global::System.ComponentModel.INotifyPropertyChanged");
                sb.AppendLine();
                Indent(sb, indent).AppendLine("{");
                indent++;
            }

            Indent(sb, indent).AppendLine("public event global::System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;");
            sb.AppendLine();
            Indent(sb, indent).AppendLine("private void __RaisePropertyChanged(string propertyName) =>");
            Indent(sb, indent + 1).AppendLine("PropertyChanged?.Invoke(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName));");

            for (int i = typeChain.Count - 1; i >= 0; i--)
            {
                indent--;
                Indent(sb, indent).AppendLine("}");
            }

            if (hasNamespace)
                sb.AppendLine("}");

            return sb.ToString();
        }

        private sealed class ClassResult
        {
            public string Namespace = "";
            public List<TypeFrame>? TypeChain;
            public Diagnostic? Diagnostic;

            public static ClassResult Success(string ns, List<TypeFrame> typeChain) =>
                new ClassResult { Namespace = ns, TypeChain = typeChain };

            public static ClassResult Error(Diagnostic diagnostic) =>
                new ClassResult { Diagnostic = diagnostic };
        }
    }
}
