using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Assisticant.SourceGenerators.GeneratorSupport;

namespace Assisticant.SourceGenerators
{
    /// <summary>
    /// Model layer. Turns an <c>[Observable]</c>-decorated partial property into a
    /// tracked property backed by <c>Observable&lt;T&gt;</c> - Assisticant's
    /// independent variables - without the user ever writing "Observable&lt;T&gt;":
    ///
    ///     [Observable] public partial string Name { get; set; }
    ///
    /// becomes an implementing partial declaration plus a hidden backing field:
    ///
    ///     private readonly Observable&lt;string&gt; __nameField = new Observable&lt;string&gt;();
    ///     public partial string Name
    ///     {
    ///         get =&gt; __nameField.Value;
    ///         set =&gt; __nameField.Value = value;
    ///     }
    ///
    /// The containing type (and every enclosing type, if nested) must be declared
    /// 'partial', and so must the property itself (that's how a generator can add a
    /// second declaration for it at all).
    ///
    /// <b>Model/ViewModel separation:</b> <c>Observable&lt;T&gt;</c> (and therefore
    /// <c>[Observable]</c>) belongs on Model classes by default - the things that hold
    /// actual mutable state - with a ViewModel deriving everything from an injected
    /// Model using <c>[Computed]</c> (see <see cref="ComputedGenerator"/>) instead.
    /// This is a strong default, not a hard rule: a ViewModel can also carry its own
    /// [Observable] state directly for things no Model would ever care about (e.g. "is
    /// this row selected"). Nothing about this generator enforces the separation either
    /// way - it works identically on a Model or a ViewModel.
    ///
    /// Add <c>[NotifyPropertyChanged]</c> to the class (see
    /// <see cref="NotifyPropertyChangedGenerator"/>) to have this property also raise
    /// <c>PropertyChanged</c> (asynchronously, via <c>UpdateScheduler</c>) when its
    /// value actually changes - including when read by a <c>[Computed]</c> property on
    /// the same class, which invalidates (and so re-raises its own PropertyChanged)
    /// exactly as it would for a dependency on an injected Model's property.
    ///
    /// <b>Constructors set immutable fields only:</b> a mutable, [Observable]-backed
    /// property is never initialized through a constructor parameter - constructors
    /// exist solely to establish a type's immutable (readonly) fields, so a Model with
    /// no immutable dependencies needs no constructor at all. Set a Model's initial
    /// state with an object initializer at the call site instead:
    ///
    ///     var person = new Person { Name = "Alice", Age = 30 };
    ///
    /// This is a prototype: it demonstrates the mechanism (attribute detection, the
    /// partial-type/partial-property requirements, and code emission) rather than a
    /// production-hardened, fully cache-friendly incremental generator (the model
    /// types below do not implement the value-equality Roslyn wants for optimal
    /// incremental caching; that only affects rebuild performance, not correctness of
    /// the generated code).
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class ObservableGenerator : IIncrementalGenerator
    {
        private const string ObservableAttributeFullName = "Assisticant.Fields.ObservableAttribute";

        private const string AttributeSource = @"// <auto-generated/>
#nullable enable

namespace Assisticant.Fields
{
    /// <summary>
    /// Generates a tracked property backed by <see cref=""Observable{T}""/> - Assisticant's
    /// independent variables. Belongs on Model classes only; see [Computed] for ViewModels.
    ///
    /// Apply it to a partial auto-property, e.g. <c>public partial string Name { get; set; }</c> -
    /// the generator supplies the implementation and a hidden Observable&lt;T&gt; field, so you
    /// never write ""Observable&lt;T&gt;"" yourself. The containing type (and every enclosing
    /// type, if nested) must be declared 'partial', and so must the property.
    ///
    /// A mutable property like this is never initialized through a constructor parameter;
    /// set initial state with an object initializer instead: new Person { Name = ""Alice"" }.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal sealed class ObservableAttribute : global::System.Attribute
    {
    }
}
";

        private static readonly DiagnosticDescriptor TypeNotPartialDiagnostic = new DiagnosticDescriptor(
            id: "ASSISTICANT001",
            title: "Containing type must be partial",
            messageFormat: "Type '{0}' must be declared 'partial' to use [Observable] on member '{1}'",
            category: "Assisticant.SourceGenerators",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor PropertyNotPartialDiagnostic = new DiagnosticDescriptor(
            id: "ASSISTICANT002",
            title: "Property must be declared partial",
            messageFormat: "Property '{0}' must be declared 'partial' to use [Observable] - a generator can only add a second declaration for it, not rewrite the one you wrote",
            category: "Assisticant.SourceGenerators",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor PropertyHasBodyDiagnostic = new DiagnosticDescriptor(
            id: "ASSISTICANT003",
            title: "Property must be an auto-property with no initializer",
            messageFormat: "Property '{0}' must be declared as 'partial {1} {0} {{ get; set; }}' with no accessor bodies and no initializer - the generator supplies the implementation. Set initial state with an object initializer at the call site instead, e.g. new Person {{ {0} = ... }}",
            category: "Assisticant.SourceGenerators",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor PropertyMissingAccessorDiagnostic = new DiagnosticDescriptor(
            id: "ASSISTICANT004",
            title: "Property must declare both get and set",
            messageFormat: "Property '{0}' must declare both a get and a set accessor to use [Observable]",
            category: "Assisticant.SourceGenerators",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx =>
                ctx.AddSource("ObservableAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

            IncrementalValuesProvider<MemberResult> results = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    ObservableAttributeFullName,
                    predicate: static (node, _) => node is PropertyDeclarationSyntax,
                    transform: static (ctx, ct) => Analyze(ctx, ct));

            context.RegisterSourceOutput(results.Collect(), static (spc, all) => Execute(spc, all));
        }

        private static MemberResult Analyze(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
        {
            var property = (IPropertySymbol)ctx.TargetSymbol;
            var location = ctx.TargetNode.GetLocation();
            var propertyDecl = (PropertyDeclarationSyntax)ctx.TargetNode;

            if (!propertyDecl.Modifiers.Any(SyntaxKind.PartialKeyword))
                return MemberResult.Error(Diagnostic.Create(PropertyNotPartialDiagnostic, location, property.Name));

            var typeChain = GetPartialTypeChainOrNull(ctx.TargetNode, property.Name, location, TypeNotPartialDiagnostic, out var typeError);
            if (typeChain == null)
                return MemberResult.Error(typeError!);

            if (propertyDecl.Initializer != null)
            {
                return MemberResult.Error(Diagnostic.Create(
                    PropertyHasBodyDiagnostic, location, property.Name, property.Type.ToDisplayString()));
            }

            var accessors = propertyDecl.AccessorList?.Accessors ?? default;
            var getAccessor = accessors.FirstOrDefault(a => a.IsKind(SyntaxKind.GetAccessorDeclaration));
            var setAccessor = accessors.FirstOrDefault(a => a.IsKind(SyntaxKind.SetAccessorDeclaration) || a.IsKind(SyntaxKind.InitAccessorDeclaration));

            if (getAccessor == null || setAccessor == null)
                return MemberResult.Error(Diagnostic.Create(PropertyMissingAccessorDiagnostic, location, property.Name));

            if (getAccessor.Body != null || getAccessor.ExpressionBody != null ||
                setAccessor.Body != null || setAccessor.ExpressionBody != null)
            {
                return MemberResult.Error(Diagnostic.Create(
                    PropertyHasBodyDiagnostic, location, property.Name, property.Type.ToDisplayString()));
            }

            var accessModifiers = propertyDecl.Modifiers
                .Where(m => !m.IsKind(SyntaxKind.PartialKeyword))
                .Select(m => m.Text);

            var elementTypeDisplay = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var backingFieldName = "__" + char.ToLowerInvariant(property.Name[0]) + property.Name.Substring(1) + "Field";
            var ns = GetNamespace(property.ContainingType);
            var notifiesPropertyChanged = property.ContainingType.GetAttributes()
                .Any(a => a.AttributeClass?.ToDisplayString() == NotifyPropertyChangedAttributeFullName);

            return MemberResult.Success(
                ns, typeChain, property.Name, elementTypeDisplay, backingFieldName,
                string.Join(" ", accessModifiers), notifiesPropertyChanged);
        }

        private static void Execute(SourceProductionContext spc, ImmutableArray<MemberResult> all)
        {
            foreach (var result in all)
            {
                if (result.Diagnostic is { } diagnostic)
                    spc.ReportDiagnostic(diagnostic);
            }

            var successes = all.Where(r => r.Diagnostic == null).ToList();

            // Group members belonging to the same (namespace, containing-type chain)
            // so each partial type gets one generated file with all of its members.
            var groups = successes.GroupBy(r => r.Namespace + "|" + string.Join("+", r.TypeChain!.Select(t => t.Name)));

            foreach (var group in groups)
            {
                var first = group.First();
                var source = RenderType(first.Namespace, first.TypeChain!, group.ToList());
                var hintName = string.Join(".", first.TypeChain!.Select(t => SanitizeForFileName(t.Name))) + ".Observable.g.cs";
                spc.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
            }
        }

        private static string RenderType(string ns, List<TypeFrame> typeChain, List<MemberResult> members)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by Assisticant.SourceGenerators.ObservableGenerator from [Observable] properties.");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(ns);
            int indent = 0;

            if (hasNamespace)
            {
                sb.Append("namespace ").Append(ns).AppendLine();
                sb.AppendLine("{");
                indent = 1;
            }

            foreach (var frame in typeChain)
            {
                Indent(sb, indent).Append("partial ").Append(frame.Keyword).Append(' ').Append(frame.Name).AppendLine();
                Indent(sb, indent).AppendLine("{");
                indent++;
            }

            foreach (var member in members)
            {
                Indent(sb, indent)
                    .Append("private readonly global::Assisticant.Fields.Observable<").Append(member.ElementType).Append("> ")
                    .Append(member.BackingFieldName)
                    .Append(" = new global::Assisticant.Fields.Observable<").Append(member.ElementType).AppendLine(">();");
                Indent(sb, indent)
                    .Append(member.AccessModifiers).Append(member.AccessModifiers.Length > 0 ? " " : "")
                    .Append("partial ").Append(member.ElementType).Append(' ').Append(member.PropertyName).AppendLine();
                Indent(sb, indent).AppendLine("{");
                Indent(sb, indent + 1).Append("get => ").Append(member.BackingFieldName).AppendLine(".Value;");

                if (member.NotifiesPropertyChanged)
                {
                    // Raised only when the value actually changes (Observable<T>.Value's
                    // own setter silently no-ops otherwise), and deferred through
                    // UpdateScheduler rather than raised inline - not because this call
                    // site itself is racy (the assignment on the line above has already
                    // completed by the time we get here), but for one uniform rule across
                    // every PropertyChanged this prototype raises, matching [Computed]'s
                    // Invalidated-driven raise, which does need to defer. See
                    // ComputedGenerator for that reasoning.
                    Indent(sb, indent + 1).AppendLine("set");
                    Indent(sb, indent + 1).AppendLine("{");
                    Indent(sb, indent + 2)
                        .Append("if (!global::System.Collections.Generic.EqualityComparer<").Append(member.ElementType)
                        .Append(">.Default.Equals(").Append(member.BackingFieldName).AppendLine(".Value, value))");
                    Indent(sb, indent + 2).AppendLine("{");
                    Indent(sb, indent + 3).Append(member.BackingFieldName).Append(".Value = value;").AppendLine();
                    Indent(sb, indent + 3)
                        .Append("global::Assisticant.UpdateScheduler.ScheduleUpdate(() => __RaisePropertyChanged(\"")
                        .Append(member.PropertyName).AppendLine("\"));");
                    Indent(sb, indent + 2).AppendLine("}");
                    Indent(sb, indent + 1).AppendLine("}");
                }
                else
                {
                    Indent(sb, indent + 1).Append("set => ").Append(member.BackingFieldName).Append(".Value = value;").AppendLine();
                }

                Indent(sb, indent).AppendLine("}");
                sb.AppendLine();
            }

            for (int i = typeChain.Count - 1; i >= 0; i--)
            {
                indent--;
                Indent(sb, indent).AppendLine("}");
            }

            if (hasNamespace)
                sb.AppendLine("}");

            return sb.ToString();
        }

        private sealed class MemberResult
        {
            public string Namespace = "";
            public List<TypeFrame>? TypeChain;
            public string PropertyName = "";
            public string ElementType = "";
            public string BackingFieldName = "";
            public string AccessModifiers = "";
            public bool NotifiesPropertyChanged;
            public Diagnostic? Diagnostic;

            public static MemberResult Success(
                string ns, List<TypeFrame> typeChain, string propertyName, string elementType, string backingFieldName,
                string accessModifiers, bool notifiesPropertyChanged) =>
                new MemberResult
                {
                    Namespace = ns,
                    TypeChain = typeChain,
                    PropertyName = propertyName,
                    ElementType = elementType,
                    BackingFieldName = backingFieldName,
                    AccessModifiers = accessModifiers,
                    NotifiesPropertyChanged = notifiesPropertyChanged,
                };

            public static MemberResult Error(Diagnostic diagnostic) =>
                new MemberResult { Diagnostic = diagnostic };
        }
    }
}
