using System;
using Assisticant;

namespace Assisticant.StoreApp.ViewModels
{
	public class ContactListNavigationModel
	{
		private Person _selectedPerson;

		#region Observable properties
		// Generated by Update Controls --------------------------------
		private Observable _indSelectedPerson = new Observable();

		public Person SelectedPerson
		{
			get { _indSelectedPerson.OnGet(); return _selectedPerson; }
			set { _indSelectedPerson.OnSet(); _selectedPerson = value; }
		}
		// End generated code --------------------------------
		#endregion
	}
}
